// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatinumCityManagement.Server.Data;

#nullable disable

namespace PlatinumCityManagement.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes", (string)null);
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.Key", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DataProtected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsX509Certificate")
                        .HasColumnType("bit");

                    b.Property<string>("Use")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Use");

                    b.ToTable("Keys", (string)null);
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Key");

                    b.HasIndex("ConsumedTime");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "b6ae90e2-c81c-444d-8aae-6fc935b403f2",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "ad2bcf0c-20db-474f-8407-5a6b159518ba"
                        },
                        new
                        {
                            UserId = "c0ffdf85-d757-4286-8e84-b16117b416c8",
                            RoleId = "bd2bcf0c-20db-474f-8407-5a6b159518bb"
                        },
                        new
                        {
                            UserId = "1c8e4151-99c2-4a65-9cf1-53ade661a38e",
                            RoleId = "b6ae90e2-c81c-444d-8aae-6fc935b403f2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PlatinumCityManagement.Server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dc5d3bf4-db4c-413d-b93a-444aeb26968d",
                            Email = "admin@localhost.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEH13g0bAiFlLRhYit2bSZzKwJAwnG6a1XwAeKlssQVyxAc/x5uI8lfkeReUvcMoZtQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "54ca81ab-d564-49b0-a9a7-d2c5f61bc38f",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        },
                        new
                        {
                            Id = "c0ffdf85-d757-4286-8e84-b16117b416c8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "21561c38-0d8c-416a-ba0a-dcc2c02c7bf2",
                            Email = "lee@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Johnny",
                            LastName = "Lee",
                            LockoutEnabled = false,
                            NormalizedEmail = "LEE@GMAIL.COM",
                            NormalizedUserName = "LEE@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIqG1wz3B5+dv2SNlTzKT2BjSP+aysjbi4NIsN+s/9ojEN//B5bnUHmC2coLvXc+9A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "afbdb317-ce92-4b29-8487-71a050f57824",
                            TwoFactorEnabled = false,
                            UserName = "lee@gmail.com"
                        },
                        new
                        {
                            Id = "1c8e4151-99c2-4a65-9cf1-53ade661a38e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "456e2fbd-9098-43cd-b36c-adb836f3c03b",
                            Email = "tan@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Yan",
                            LastName = "Teo",
                            LockoutEnabled = false,
                            NormalizedEmail = "TAN@GMAIL.COM",
                            NormalizedUserName = "TAN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEF1+nJNvZY7Dr4b88TNyhVFQul27TLY3yl3WbZO1DxeY0eXAxi9cs6oQoLCRh3ddfA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "36772b0b-8790-4973-88f1-f25ddad42bcd",
                            TwoFactorEnabled = false,
                            UserName = "tan@gmail.com"
                        });
                });

            modelBuilder.Entity("PlatinumCityManagement.Shared.Domain.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeatNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SeatQty")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StaffId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("PlatinumCityManagement.Shared.Domain.CinemaBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HallQuantity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CinemaBranches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Tampines",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(5683),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(5685),
                            HallQuantity = 9,
                            Name = "Platinum City Tampines",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Bedok",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(5688),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(5689),
                            HallQuantity = 10,
                            Name = "Platinum City Bedok",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Jewel Changi Airport",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(5692),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(5692),
                            HallQuantity = 8,
                            Name = "Platinum City Jewel",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("PlatinumCityManagement.Shared.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "707 Tampines Street 71 #09-20, 520707",
                            ContactNumber = "89220951",
                            DOB = new DateTime(2005, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "lee@gmail.com",
                            MembershipType = "Platinum",
                            Name = "Johnny Lee",
                            Points = 133
                        },
                        new
                        {
                            Id = 2,
                            Address = "707 Geylang Street 71 #02-20, 520707",
                            ContactNumber = "89235451",
                            DOB = new DateTime(2002, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "tan@gmail.com",
                            MembershipType = "Platinum",
                            Name = "Tan",
                            Points = 192
                        });
                });

            modelBuilder.Entity("PlatinumCityManagement.Shared.Domain.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<int?>("CinemaBranchId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreeningQuality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CinemaBranchId");

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 100,
                            CinemaBranchId = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6007),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6010),
                            Name = "1",
                            ScreeningQuality = "IMAX",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 90,
                            CinemaBranchId = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6013),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6014),
                            Name = "1",
                            ScreeningQuality = "DOLBY ATMOS",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 80,
                            CinemaBranchId = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6016),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6017),
                            Name = "1",
                            ScreeningQuality = "HD",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("PlatinumCityManagement.Shared.Domain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cast")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Poster")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Review")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cast = "Brie Larson, Teyonah Parris, Iman Vellani",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = "1h 45mins",
                            MovieDescription = "Brie Larson, Iman Vellani, and director Nia DaCosta surprised fans across the country. Carol Danvers AKA Captain Marvel has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe.",
                            Poster = "/posters/marvels.jpeg",
                            Rating = "5.0",
                            Review = "okok",
                            Title = "The Marvels"
                        },
                        new
                        {
                            Id = 2,
                            Cast = "Margot Robbie, Ryan Gosling",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = "1h 33mins",
                            MovieDescription = "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
                            Poster = "/posters/barbie.jpg",
                            Rating = "3.9",
                            Review = "meh",
                            Title = "Barbie"
                        },
                        new
                        {
                            Id = 3,
                            Cast = "Timothee Chalemet",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = "1h 30mins",
                            MovieDescription = "With dreams of opening a shop in a city renowned for its chocolate, a young and poor Willy Wonka discovers that the industry is run by a cartel of greedy chocolatiers.",
                            Poster = "/posters/wonka.jpg",
                            Rating = "2.0",
                            Review = "eeee",
                            Title = "Wonka"
                        },
                        new
                        {
                            Id = 4,
                            Cast = "David S. Goyer",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = "1h 13mins",
                            MovieDescription = "Blade, now a wanted man by the FBI, must join forces with the Nightstalkers to face his most challenging enemy yet: Dracula.",
                            Poster = "/posters/blade3.jpg",
                            Rating = "2.3",
                            Review = "ok",
                            Title = "Blade"
                        },
                        new
                        {
                            Id = 5,
                            Cast = "Alexander Skarsgård, Millie Bobbie Brown",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = "1h 33mins",
                            MovieDescription = "The epic next chapter in the cinematic Monsterverse pits two of the greatest icons in motion picture history against each other--the fearsome Godzilla and the mighty Kong--with humanity caught in the balance.",
                            Poster = "/posters/godzillaa.jpg",
                            Rating = "2.3",
                            Review = "ok only",
                            Title = "Godzilla"
                        },
                        new
                        {
                            Id = 6,
                            Cast = "Gong Yoo, Jung Yumi, Ma Dong Seok",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = "1h 43mins",
                            MovieDescription = "While a zombie virus breaks out in South Korea, passengers struggle to survive on the train from Seoul to Busan.",
                            Poster = "/posters/traintobusan.jpg",
                            Rating = "4.8",
                            Review = "nice",
                            Title = "Train To Busan"
                        },
                        new
                        {
                            Id = 7,
                            Cast = "Albert Brooks",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = "1h 23mins",
                            MovieDescription = "After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.",
                            Poster = "/posters/nemo.jpg",
                            Rating = "4.9",
                            Review = "amazing",
                            Title = "Nemo"
                        },
                        new
                        {
                            Id = 8,
                            Cast = "Ryan Reynolds",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = "1h 54mins",
                            MovieDescription = "A wisecracking mercenary gets experimented on and becomes immortal yet hideously scarred, and sets out to track down the man who ruined his looks.",
                            Poster = "/posters/deadpool.jpg",
                            Rating = "3.9",
                            Review = "not bad",
                            Title = "Deadpool"
                        });
                });

            modelBuilder.Entity("PlatinumCityManagement.Shared.Domain.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HallId")
                        .HasColumnType("int");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("Showtime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.HasIndex("MovieId");

                    b.ToTable("Screenings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6309),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6312),
                            HallId = 1,
                            MovieId = 1,
                            Price = 10,
                            Showtime = new DateTime(2024, 2, 3, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6316),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6316),
                            HallId = 2,
                            MovieId = 1,
                            Price = 12,
                            Showtime = new DateTime(2024, 2, 4, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6319),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6320),
                            HallId = 3,
                            MovieId = 1,
                            Price = 15,
                            Showtime = new DateTime(2024, 2, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("PlatinumCityManagement.Shared.Domain.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ScreeningId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SeatTaken")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScreeningId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6606),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6608),
                            ScreeningId = 1,
                            SeatNo = "A1",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6611),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6612),
                            ScreeningId = 1,
                            SeatNo = "A2",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6614),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6614),
                            ScreeningId = 1,
                            SeatNo = "A3",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6616),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6617),
                            ScreeningId = 1,
                            SeatNo = "A4",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6619),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6631),
                            ScreeningId = 1,
                            SeatNo = "A5",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6650),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6651),
                            ScreeningId = 1,
                            SeatNo = "A6",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6653),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6654),
                            ScreeningId = 1,
                            SeatNo = "A7",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6656),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6657),
                            ScreeningId = 1,
                            SeatNo = "A8",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6659),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6660),
                            ScreeningId = 1,
                            SeatNo = "A9",
                            SeatTaken = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6662),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6662),
                            ScreeningId = 1,
                            SeatNo = "A10",
                            SeatTaken = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 21,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6664),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6665),
                            ScreeningId = 2,
                            SeatNo = "A1",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 22,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6667),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6667),
                            ScreeningId = 2,
                            SeatNo = "A2",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 23,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6669),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6670),
                            ScreeningId = 2,
                            SeatNo = "A3",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 24,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6672),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6673),
                            ScreeningId = 2,
                            SeatNo = "A4",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 25,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6675),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6675),
                            ScreeningId = 2,
                            SeatNo = "A5",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 26,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6740),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6741),
                            ScreeningId = 2,
                            SeatNo = "A6",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 27,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6743),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6744),
                            ScreeningId = 2,
                            SeatNo = "A7",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 28,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6746),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6747),
                            ScreeningId = 2,
                            SeatNo = "A8",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 29,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6749),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6749),
                            ScreeningId = 2,
                            SeatNo = "A9",
                            SeatTaken = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 30,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6751),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6752),
                            ScreeningId = 2,
                            SeatNo = "A10",
                            SeatTaken = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 31,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6754),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6755),
                            ScreeningId = 3,
                            SeatNo = "A1",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 32,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6757),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6757),
                            ScreeningId = 3,
                            SeatNo = "A2",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 33,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6759),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6760),
                            ScreeningId = 3,
                            SeatNo = "A3",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 34,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6762),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6763),
                            ScreeningId = 3,
                            SeatNo = "A4",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 35,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6765),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6765),
                            ScreeningId = 3,
                            SeatNo = "A5",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 36,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6767),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6768),
                            ScreeningId = 3,
                            SeatNo = "A6",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 37,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6770),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6770),
                            ScreeningId = 3,
                            SeatNo = "A7",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 38,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6773),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6773),
                            ScreeningId = 3,
                            SeatNo = "A8",
                            SeatTaken = false,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 39,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6775),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6776),
                            ScreeningId = 3,
                            SeatNo = "A9",
                            SeatTaken = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 40,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6778),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(6778),
                            ScreeningId = 3,
                            SeatNo = "A10",
                            SeatTaken = true,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("PlatinumCityManagement.Shared.Domain.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CinemaBranchId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PerformanceRating")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CinemaBranchId")
                        .IsUnique();

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "499B Tampines Ave 9, #08-238, Singapore 522499",
                            CinemaBranchId = 1,
                            ContactNumber = "81207097",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(5330),
                            DateUpdated = new DateTime(2024, 2, 4, 17, 37, 33, 857, DateTimeKind.Local).AddTicks(5353),
                            EmailAddress = "John@platinumcity.com",
                            Name = "John",
                            PerformanceRating = 5,
                            Role = "Manager",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PlatinumCityManagement.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PlatinumCityManagement.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlatinumCityManagement.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PlatinumCityManagement.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlatinumCityManagement.Shared.Domain.Booking", b =>
                {
                    b.HasOne("PlatinumCityManagement.Shared.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlatinumCityManagement.Shared.Domain.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PlatinumCityManagement.Shared.Domain.Hall", b =>
                {
                    b.HasOne("PlatinumCityManagement.Shared.Domain.CinemaBranch", "CinemaBranch")
                        .WithMany()
                        .HasForeignKey("CinemaBranchId");

                    b.Navigation("CinemaBranch");
                });

            modelBuilder.Entity("PlatinumCityManagement.Shared.Domain.Screening", b =>
                {
                    b.HasOne("PlatinumCityManagement.Shared.Domain.Hall", "Hall")
                        .WithMany()
                        .HasForeignKey("HallId");

                    b.HasOne("PlatinumCityManagement.Shared.Domain.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId");

                    b.Navigation("Hall");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("PlatinumCityManagement.Shared.Domain.Seat", b =>
                {
                    b.HasOne("PlatinumCityManagement.Shared.Domain.Screening", "Screening")
                        .WithMany()
                        .HasForeignKey("ScreeningId");

                    b.Navigation("Screening");
                });

            modelBuilder.Entity("PlatinumCityManagement.Shared.Domain.Staff", b =>
                {
                    b.HasOne("PlatinumCityManagement.Shared.Domain.CinemaBranch", "CinemaBranch")
                        .WithOne("Staff")
                        .HasForeignKey("PlatinumCityManagement.Shared.Domain.Staff", "CinemaBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CinemaBranch");
                });

            modelBuilder.Entity("PlatinumCityManagement.Shared.Domain.CinemaBranch", b =>
                {
                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
